In [2]:
import numpy as np 
import time
import sys

In [3]:
arr = np.array([1,2 ,3 ,4 ,5, 6])

In [4]:
print(arr)

[1 2 3 4 5 6]


In [5]:
#To create a 3x4 matrix all of its elements consisting of 1 we use the np.ones function:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
#To create an array with the same dimensions with all elements of 0, we use the np.zeros function:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
#To create an array of 2 rows and 3 columns with all elements of a number that we specify, we use the np.full function:
np.full((2,2), 10)


array([[10, 10],
       [10, 10]])

In [8]:
#To obtain an array that starts from one number and ends with a value before another number with step specifying we use the np.arange function:
np.arange(5, 30, 5)

array([ 5, 10, 15, 20, 25])

In [9]:
#To obtain an array that begins with a certain number and ends with another number, with specifying the number of elements of the matrix so that the value of its elements is between the two numbers, we use the np.linespace function:
np.linspace(1,5,5)


array([1., 2., 3., 4., 5.])

In [10]:
# Importing data from the file into the work environment:
id, mobile, com = np.loadtxt('data.txt',skiprows=2,unpack=True)

In [11]:
print(id, mobile, com)

[1. 2. 3. 4. 5.] [  555.  9999.  6565.   888. 74744.] [0.2 0.1 0.2 0.2 0.3]


In [12]:
# Export arrays to external files
x = np.arange(0,5,1)
np.savetxt('test.txt', x, delimiter = ',') 

In [13]:
elements = 1500000

my_list1 = range(elements)
my_list2 = range(elements)

my_array1 = np.arange(elements)
my_array2 = np.arange(elements)


In [14]:
list_start = time.time()
list_result = [(n1 + n2) for n1, n2 in zip(my_list1, my_list2)]
print(f"List Time: {time.time() - list_start}")

array_start = time.time()
array_result = my_array1 + my_array2
print(f"Array Time: {time.time() - array_start}")

List Time: 0.40975046157836914
Array Time: 0.004999876022338867
